Support for querying the reflect reporting API
reflect/reflect-node pull request #3
Opened 2018-03-23 23:08 UTC by cp

- [x] Setup eslint and circleci
- [x] Add reporting namespace
- [x] Update README with documentation

2018-03-23 23:35 UTC, bradhe requested changes
Minor thing

2018-03-23 23:35 UTC, bradhe commented on README.md
> +`connectionSlug` | string | The connection slug you wish to query
This isn't the connection you want to query, but rather the data model (project) you want to query.

2018-03-23 23:35 UTC, bradhe commented on README.md
> +    console.log('data');
quotes here.

2018-03-23 23:35 UTC, bradhe commented on src/client/reporting.js
> +Reporting.prototype.report = function report(connectionSlug, dimensions, metrics, options = {}) {
also project/data model instead of connection slug.

2018-03-27 18:26 UTC, woodburndesigns approved these changes

2018-03-27 18:26 UTC, merged